- name: conditions demo
  hosts: local
  connection: local
  vars:
   NUMBER: 89
  tasks:
  - name: print the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "The number is {{ NUMBER }} and it is less than or equal to 100.
    when: NUMBER <= 100
    
  - name: print the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "The number is {{ NUMBER }} and it is less than or equal to 100.
    when: NUMBER >= 100