- name: user creation
  host: local
  connection: local
  tasks:
   - name: check roboshop user exists or not
     ansible.builtin.command: id roboshop
     register: output
     ignore_errors: true

   - name: create user
     ansible.builtin.command: useradd roboshop
     become: yes
     when: output.rc !=0 # it means above task failure

   - name: user already exists or not
     ansible.builtin.debug:
       msg: "user already exists"
     when: output.rc ==0